http://localhost:3333/areas
http://localhost:3333/campus
http://localhost:3333/cursos
http://localhost:3333/laboratorios
http://localhost:3333/predios
http://localhost:3333/vagas_ic
http://localhost:3333/inscricoes_ic